name: ledgerlint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup ledgerlint
      run: |
        mkdir -p "${HOME}/.local/bin/"
        wget https://oshikiri.github.io/ledgerlint/install.bash
        bash ./install.bash

    - name: Run ledgerlint
      run: |
        export PATH+=":${HOME}/.local/bin/"
        ledgerlint -h
